### ISSUE TITLE
Tried it and got a stack trace

### ISSUE THREAD

**Issue by forrcaho** [handsontable/hot-builder#1]
Here's what happened when I tried to use hot-builder on OS X:

I entered this command:

```
emerald:HandsontableTest fcahoon$ hot-builder build -o lib
```

Received this prompt:

```
? Select modules that will be used to build your custom Handsontable distribution package: (Press <space> to select)
 ──────────────
 External libraries:
❯◯ jquery-ui
 ◯ shims
 ◯ moment
 ◯ pikaday
 ◯ zeroclipboard
```

I chose jquery-ui (also tried several others, with the same error result):

```
? Select modules that will be used to build your custom Handsontable distribution package: 
Creating custom build (Handsontable v0.14.1)...

Founded 0 plugins

/usr/local/lib/node_modules/hot-builder/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/hot-builder/node_modules/handsontable/intro.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at JSWorker.run (/usr/local/lib/node_modules/hot-builder/lib/workers/js-worker.js:69:14)
    at /usr/local/lib/node_modules/hot-builder/lib/worker.js:73:12
    at /usr/local/lib/node_modules/hot-builder/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/hot-builder/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/hot-builder/node_modules/async/lib/async.js:124:9)
    at Worker.run (/usr/local/lib/node_modules/hot-builder/lib/worker.js:72:9)
emerald:HandsontableTest fcahoon$ 
```

Note, the intro.js file indeed does not exist. Here's what I have in the directory where it was supposed to be:

```
emerald:HandsontableTest fcahoon$ ls -F /usr/local/lib/node_modules/hot-builder/node_modules/handsontable
CHANGELOG.md            README.md           index.html          sauce_connect.log
CNAME               bower.json          index.html.orig         src/
CONTRIBUTING.md         demo/               lib/                test/
Gruntfile.js            dist/               package.json            update.json
LICENSE             handsontable.jquery.json    plugins/
```

**Comment by budnix** [comment]
Hi,

Thanks for reporting. I have updated hot-builder to 0.1.5. Now everything should be working as expected.

But keep in mind that this version is for testing proposes. Next week we are planning release with modularized version of Handsontable which is required by hot-builder. Actually builder uses develop branch.
